# プラグイン管理
[[plugins]]
repo = 'Shougo/dein.vim'

# 非同期でインストールできるようになるやつ
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# ナードツリー
[[plugins]]
repo = 'scrooloose/nerdtree'

# vifm用
# [[plugins]]
# repo = 'vifm/neovim-vifm'

# vimのファイラ
# [[plugins]]
# repo = 'cocopon/vaffle.vim'

# 実質これしかnvimのファイラない
# [[plugins]]
# repo = 'Shougo/vimfiler.vim'
# on_source = ['unite.vim']

# vimfilerで必用になるため仕方ない
# [[plugins]]
# repo = 'Shougo/unite.vim'

# 最近開いたファイルをdeniteで使うため
[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1
on_source = ['unite.vim', 'denite.nvim']

# ヤンクの履歴をdeniteで使うため
[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_source = ['unite.vim', 'denite.nvim']

# 昔のunite.vim
[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_event = 'BufRead'

# コード補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'

# インデントを可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# 無駄な空白をハイライト
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# statusline
# [[plugins]]
# repo = 'itchyny/lightline.vim'

# colorschema
[[plugins]]
repo = 'altercation/vim-colors-solarized'

# j, k移動高速化
[[plugins]]
repo = 'rhysd/accelerated-jk'

# 閉じカッコ自動
[[plugins]]
repo = 'cohama/lexima.vim'


# gcc で現在行をコメントアウト。 選択してgcで複数行。
[[plugins]]
repo = 'tomtom/tcomment_vim'

# ctag使えるようにする
[[plugins]]
repo = 'szw/vim-tags'

# gitをvimで
[[plugins]]
repo = "tpope/vim-fugitive"

# ファイルの変更したところを表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

# ターミナルをvimから
[[plugins]]
repo = "kassio/neoterm"

# ウインドウのリサイズ
[[plugins]]
repo = 'simeji/winresizer'

# シンタックスチェック
[[plugins]]
repo = 'vim-syntastic/syntastic'

# ステータスバーをかっこよくする
[[plugins]]
repo = 'vim-airline/vim-airline'

# ステータスバーテーマ
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# vimとtmuxのシームレス移動
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'

# 囲み文字を変更
[[plugins]]
repo='tpope/vim-surround'
